# ADA Semester Project

This represents the project for the CS-401 course at EPFL, done by:

| SCIPER                                              | Name                      |
|:----------------------------------------------------|:--------------------------|
| [356420](https://people.epfl.ch/badr.almahouri)     | Badr Al Mahouri           |
| [341237](https://people.epfl.ch/louis.grange)       | Louis Grange              |
| [340497](https://people.epfl.ch/daniel.alvesataide) | Daniel Ataíde             |
| [329310](https://people.epfl.ch/arnaud.tadic)       | Arnaud Jacques Yves Tadic |
| [308396](https://people.epfl.ch/yuri.cho)           | Yuri Cho                  |

---

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import src.utils as utils

In [6]:
body_data, title_data, subreddits_data, users_data = utils.load_data()

In [7]:
body_data

,SOURCE_SUBREDDIT,TARGET_SUBREDDIT,POST_ID,TIMESTAMP,LINK_SENTIMENT,PROPERTIES
0,leagueoflegends,teamredditteams,1u4nrps,2013-12-31 16:39:58,1,"345.0,298.0,0.75652173913,0.0173913043478,0.08..."
1,theredlion,soccer,1u4qkd,2013-12-31 18:18:37,-1,"101.0,98.0,0.742574257426,0.019801980198,0.049..."
2,inlandempire,bikela,1u4qlzs,2014-01-01 14:54:35,1,"85.0,85.0,0.752941176471,0.0235294117647,0.082..."
3,nfl,cfb,1u4sjvs,2013-12-31 17:37:55,1,"1124.0,949.0,0.772241992883,0.0017793594306,0...."
4,playmygame,gamedev,1u4w5ss,2014-01-01 02:51:13,1,"715.0,622.0,0.777622377622,0.00699300699301,0...."
...,...,...,...,...,...,...
286556,negareddit,debatefascism,68im20s,2017-04-30 16:31:26,1,"441.0,405.0,0.775510204082,0.0294784580499,0.0..."
286557,mildlynomil,justnomil,68imlas,2017-04-30 04:19:03,1,"2226.0,1855.0,0.786163522013,0.00224618149146,..."
286558,mmorpg,blackdesertonline,68ip5os,2017-04-30 16:54:08,1,"1100.0,909.0,0.778181818182,0.00181818181818,0..."
286559,electricskateboards,askreddit,68ipb2s,2017-04-30 16:41:53,1,"1876.0,1567.0,0.78144989339,0.00692963752665,0..."
286560,mgtow,dataisbeautiful,68ipeos,2017-04-30 16:52:59,1,"1129.0,975.0,0.795394154119,0.0150575730735,0...."

In [8]:
title_data

,SOURCE_SUBREDDIT,TARGET_SUBREDDIT,POST_ID,TIMESTAMP,LINK_SENTIMENT,PROPERTIES
0,rddtgaming,rddtrust,1u4pzzs,2013-12-31 16:39:18,1,"25.0,23.0,0.76,0.0,0.44,0.12,0.12,4.0,4.0,0.0,..."
1,xboxone,battlefield_4,1u4tmfs,2013-12-31 17:59:11,1,"100.0,88.0,0.78,0.02,0.08,0.13,0.07,16.0,16.0,..."
2,ps4,battlefield_4,1u4tmos,2013-12-31 17:59:40,1,"100.0,88.0,0.78,0.02,0.08,0.13,0.07,16.0,16.0,..."
3,fitnesscirclejerk,leangains,1u50xfs,2013-12-31 19:01:56,1,"49.0,43.0,0.775510204082,0.0,0.265306122449,0...."
4,fitnesscirclejerk,lifeprotips,1u51nps,2013-12-31 21:02:28,1,"14.0,14.0,0.785714285714,0.0,0.428571428571,0...."
...,...,...,...,...,...,...
571922,seattleshitshow,seattlewa,68iptp,2017-04-27 11:07:31,-1,"83.0,70.0,0.78313253012,0.0,0.10843373494,0.16..."
571923,peoplewhosayheck,spiderman,68iqh6s,2017-04-30 16:36:07,1,"121.0,105.0,0.719008264463,0.0165289256198,0.0..."
571924,vzla,wtf,68iqkcs,2017-04-30 15:50:07,1,"68.0,58.0,0.764705882353,0.0,0.147058823529,0...."
571925,denverbroncos,nfl,68iqt8,2017-04-30 16:11:30,-1,"96.0,79.0,0.770833333333,0.0,0.0729166666667,0..."
571926,shitpoliticssays,politicaldiscussion,68ir4os,2017-04-30 15:14:05,1,"140.0,122.0,0.8,0.0,0.114285714286,0.135714285..."

In [9]:
subreddits_data

,spiders,0.158972,0.285813,0.226329,-0.183338,-0.163159,-0.18891,0.422705,0.168602,0.178193,...,-0.025041,0.184655,0.111942,-1.125799,0.223129,-0.387323,-0.234882,-0.252297,-0.054315,0.500009
0,askreddit,-0.499114,0.323983,-0.424809,-0.222705,-0.327201,0.412856,1.040088,0.996697,-1.256240,...,0.072151,0.226658,0.535705,0.039861,-0.027087,-0.239952,0.554510,0.676439,-0.328846,0.941547
1,globaloffensivetrade,-0.023145,-1.199374,1.661484,-1.025296,1.424670,-1.179507,-1.035703,0.329301,-0.567272,...,2.998430,-1.235703,-0.326850,4.381238,-1.965378,-2.369674,-0.615389,2.010601,-0.919314,-2.149625
2,fireteams,2.492506,-2.529917,-0.448484,-3.543441,-0.586122,-0.101517,1.837567,-0.215715,-2.460388,...,-1.875214,0.969291,0.497958,2.941132,2.423561,1.315691,-0.959618,0.151845,-0.852492,-0.467526
3,funny,-0.819370,-0.865261,0.301753,0.018787,0.201029,0.070462,0.903895,1.038460,-0.306950,...,1.364194,0.830233,-0.137822,-2.204667,-0.162008,0.390291,-0.556404,0.322684,0.641634,1.320716
4,the_donald,-0.123265,-0.610208,0.361495,-1.171773,0.367407,0.624919,2.420601,-0.447998,1.393862,...,0.981761,1.044754,-2.334628,-0.005856,-1.647531,-0.139574,-0.284726,0.315069,-0.846018,0.800535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51272,33rd,-0.000076,-0.001643,-0.002896,0.000581,-0.003509,-0.000827,0.002095,0.000123,0.004370,...,-0.001570,-0.002246,0.003491,-0.004310,0.001598,0.005168,-0.001156,0.001575,-0.001938,0.001594
51273,bestofvic2015,-0.000203,0.012698,-0.007575,0.006486,-0.001693,0.004743,-0.002401,0.000121,0.001600,...,0.001392,0.001258,0.002970,-0.014106,-0.002713,-0.008648,0.003660,-0.005755,-0.001790,-0.001313
51274,aberystwyth,-0.001563,0.004733,-0.000082,-0.000982,-0.001511,0.001285,0.002187,0.002967,0.000660,...,0.002213,0.000520,-0.000564,-0.010018,0.002507,-0.000651,0.004169,-0.004672,0.002371,0.001073
51275,mail_forwarding,0.009269,0.024779,-0.017018,-0.007228,0.002351,0.003462,-0.008446,0.004544,0.022505,...,-0.002591,0.003482,0.001042,-0.002796,0.010739,-0.009148,0.000363,-0.003144,0.001945,-0.017272
51276,cover,0.004570,0.012403,-0.000363,-0.002496,0.003831,0.005336,-0.005552,0.003872,0.005270,...,0.003453,-0.000205,0.003384,-0.008668,0.000594,-0.003586,0.005635,-0.000203,0.003747,0.000365

In [10]:
users_data

,rotoreuters,-0.224305,0.034301,-0.082651,0.004676,0.00696,0.892179,-0.309423,0.570185,0.49211,...,-0.380348,-0.14416,-0.289317,0.471727,-0.174092,0.534364,0.218821,0.269216,-0.412621,-0.469088
0,fiplefip,-0.306765,0.259314,-0.950335,0.560013,-0.364981,0.073359,-0.256642,-0.348088,-0.030323,...,-0.432182,-0.769793,-0.434484,0.268733,-0.163076,-0.455654,0.416560,-0.219805,-0.568944,-0.477788
1,amici_ursi,-0.234556,0.609160,-0.065395,-0.212264,0.269761,-0.562834,-0.455435,-0.349673,0.391979,...,0.622636,0.234270,0.083597,-0.647548,0.103007,0.344196,0.140004,0.579194,-0.046483,-0.705478
2,unremovable,0.253033,0.548086,-0.538728,0.375164,-0.129068,0.307664,-0.047697,-0.492977,0.224615,...,0.165165,-0.216920,-0.414641,-0.144242,0.185060,0.356242,0.095848,0.403010,-0.320782,-0.735368
3,CDRE_64,-0.008056,0.050560,-0.295054,-0.046483,0.042420,0.345231,0.075705,-0.198281,0.139585,...,-0.221219,-0.474621,-0.149465,-0.156034,-0.115828,-0.170805,0.284541,-0.144770,-0.050010,-0.341634
4,noeatnosleep,0.313406,0.702873,0.076761,-0.511176,0.374304,-0.247656,0.148855,-0.616189,-0.144205,...,-0.132059,0.253945,-0.525948,-0.017446,-0.387158,-0.816076,0.710558,-0.235635,-0.339882,-0.378385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118375,rajkumareco,-0.069814,0.023679,0.032822,-0.200074,0.064771,0.157998,0.053184,-0.124960,-0.068105,...,-0.030709,-0.097185,0.029929,-0.067463,-0.265459,-0.201405,0.254439,0.006016,0.013839,0.105910
118376,roryswife,-0.102751,-0.008857,-0.131908,-0.154319,-0.023083,0.022363,0.090508,-0.034480,-0.033439,...,-0.084732,-0.160888,-0.036171,-0.049265,-0.040469,-0.160486,0.059213,0.051630,0.093915,-0.017583
118377,shillagepeople,0.008636,0.067610,-0.133499,-0.057814,0.047882,0.027176,0.047853,-0.066698,-0.047510,...,-0.031517,-0.191591,-0.032287,0.034490,-0.041353,-0.125495,0.162754,0.004968,-0.006810,-0.037618
118378,trizock,0.101569,0.050567,-0.096631,-0.068904,-0.047230,0.123565,-0.131402,-0.131583,-0.143453,...,-0.076321,0.071303,-0.040878,0.047556,0.079397,-0.050565,0.107052,0.139607,-0.064489,-0.177276
118379,zenlogick,-0.059097,0.077194,-0.012921,-0.160951,-0.069518,0.000862,-0.043677,-0.037674,-0.162978,...,-0.011093,-0.218056,0.015643,0.053693,-0.047626,0.090370,-0.042760,-0.027736,0.011910,-0.159299