# Soccer Teams Exploratory Data Analysis (EDA)

In [ ]:
# Automatically reloads modules when you make changes (useful during development)
%load_ext autoreload
%autoreload 2

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sys, os
sys.path.append(os.path.abspath('..'))

from src.data import load_data
df_body, df_title, df_subreddits, df_english_pl, df_esports, df_superbowl = load_data()

In [4]:
df_english_pl

,Season,DateTime,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR
0,2013-14,2014-01-01T00:00:00Z,Arsenal,Cardiff,2,0,H,0.0,0.0,D,...,6.0,2.0,12.0,2.0,6.0,11.0,1.0,2.0,0.0,0.0
1,2013-14,2014-01-01T00:00:00Z,Crystal Palace,Norwich,1,1,D,1.0,1.0,D,...,4.0,5.0,9.0,4.0,12.0,10.0,2.0,1.0,0.0,1.0
2,2013-14,2014-01-01T00:00:00Z,Fulham,West Ham,2,1,H,1.0,1.0,D,...,11.0,3.0,12.0,4.0,6.0,5.0,2.0,1.0,0.0,1.0
3,2013-14,2014-01-01T00:00:00Z,Liverpool,Hull,2,0,H,1.0,0.0,H,...,6.0,0.0,3.0,4.0,15.0,15.0,1.0,2.0,0.0,0.0
4,2013-14,2014-01-01T00:00:00Z,Man United,Tottenham,1,2,A,0.0,1.0,A,...,6.0,4.0,13.0,2.0,7.0,7.0,2.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1284,2016-17,2017-04-29T00:00:00Z,Crystal Palace,Burnley,0,2,A,0.0,1.0,A,...,5.0,3.0,14.0,4.0,11.0,12.0,2.0,0.0,0.0,0.0
1285,2016-17,2017-04-29T00:00:00Z,Southampton,Hull,0,0,D,0.0,0.0,D,...,2.0,1.0,6.0,6.0,9.0,13.0,0.0,3.0,0.0,0.0
1286,2016-17,2017-04-29T00:00:00Z,Stoke,West Ham,0,0,D,0.0,0.0,D,...,4.0,4.0,5.0,3.0,12.0,3.0,1.0,0.0,0.0,0.0
1287,2016-17,2017-04-29T00:00:00Z,Sunderland,Bournemouth,0,1,A,0.0,0.0,D,...,5.0,7.0,6.0,5.0,13.0,9.0,3.0,2.0,0.0,0.0
1288,2016-17,2017-04-29T00:00:00Z,West Brom,Leicester,0,1,A,0.0,1.0,A,...,4.0,1.0,5.0,6.0,14.0,9.0,2.0,2.0,0.0,0.0

In [5]:
df_superbowl

,Date,SB,Winner,Winner Pts,Loser,Loser Pts,MVP,Stadium,City,State
0,Feb 5 2017,LI (51),New England Patriots,34,Atlanta Falcons,28,Tom Brady,NRG Stadium,Houston,Texas
1,Feb 7 2016,50,Denver Broncos,24,Carolina Panthers,10,Von Miller,Levi's Stadium,Santa Clara,California
2,Feb 1 2015,XLIX (49),New England Patriots,28,Seattle Seahawks,24,Tom Brady,University of Phoenix Stadium,Glendale,Arizona
3,Feb 2 2014,XLVIII (48),Seattle Seahawks,43,Denver Broncos,8,Malcolm Smith,MetLife Stadium,East Rutherford,New Jersey

In [6]:
# For title dataset
source_title_subs = df_title["SOURCE_SUBREDDIT"].unique()
target_title_subs = df_title["TARGET_SUBREDDIT"].unique()

# For body dataset
source_body_subs = df_body["SOURCE_SUBREDDIT"].unique()
target_body_subs = df_body["TARGET_SUBREDDIT"].unique()

print("SOURCE (title):", source_title_subs)
print("TARGET (title):", target_title_subs)
print("SOURCE (body):", source_body_subs)
print("TARGET (body):", target_body_subs)

SOURCE (title): ['rddtgaming' 'xboxone' 'ps4' ... 'uplifting_news' 'medicinalherbs'
 'mintsim']
TARGET (title): ['rddtrust' 'battlefield_4' 'leangains' ... 'seriousvr' 'mattgray'
 'noshitouija']
SOURCE (body): ['leagueoflegends' 'theredlion' 'inlandempire' ... 'daddyofive'
 'noshitouija' 'mildlynomil']
TARGET (body): ['teamredditteams' 'soccer' 'bikela' ... 'hatedaddyofive' 'ouija_irl'
 'wholesomeouija']

In [8]:
subreddit = "nfl"
# subreddit = "hockey"
# subbredit = "nba"
# subreddit = "baseball"
# subreddit = "cfb"